### ISSUE TITLE
Error getting votes by post ID

### ISSUE THREAD

**Issue by annelorraineuy** [forceapple/social_media#6]
Errors on GET phase 3

Can't find Noni()

UPDATE: Sometimes # of comments work!

![screen shot 2015-05-21 at 2 51 47 pm](https://cloud.githubusercontent.com/assets/5892190/7759680/64681272-ffc8-11e4-8d6b-ef3946dc6760.png)

![screen shot 2015-05-21 at 2 53 45 pm](https://cloud.githubusercontent.com/assets/5892190/7759712/92bfd8f8-ffc8-11e4-9b9e-f2c90595568f.png)

**Comment by forceapple** [comment]
if it's a class from model, I commented out Noni class in model.
